// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func About() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = Base("CY_BORGER - About", nil, AboutContent()).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func AboutContent() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"container text-left\" style=\"max-width: 600px; margin: 0 auto; padding-top: 2rem;\"><h1 class=\"text-accent mb-lg\">ABOUT CY_BORGER</h1><div class=\"card mb-md\"><h3 class=\"text-success mb-sm\">THE PROJECT</h3><p class=\"mb-sm\">CY_BORGER is an open-source character generator and game management tool for the CY_BORG RPG.</p><p><a href=\"https://github.com/mrpoundsign/cy_borger\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"text-accent no-decoration\">🔗 View on GitHub</a></p></div><div class=\"card mb-md\"><h3 class=\"text-warning mb-sm\">ATTRIBUTION</h3><p class=\"mb-sm\">Full attribution and credit goes to <strong>makedatanotlore</strong> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs("for")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/about.templ`, Line: 19, Col: 96}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " the incredible character generation logic and data sets that make this tool possible.</p><p><a href=\"https://linktr.ee/makedatanotlore\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"text-warning no-decoration\">🔗 Support makedatanotlore</a></p></div><div class=\"card mb-md\"><h3 class=\"text-danger mb-sm\">CY_BORG</h3><p class=\"text-muted text-sm mb-sm\">CY_BORG is a game by Christian Sahlén and Johan Nohr.  CY_BORGER is an independent production and is not affiliated with Ockult Örtmästare Games or Stockholm Kartell.</p><p><a href=\"https://cy-borg.io/\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"text-danger no-decoration\">🔗 Official CY_BORG Website</a></p></div><div class=\"text-center mt-lg\"><a href=\"/\" class=\"btn-outline-small\">← BACK TO HOME</a></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
