// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "fmt"

func Error(statusCode int, errorMessage string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", statusCode))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/error.templ`, Line: 11, Col: 40}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " - ERROR</title><link rel=\"icon\" type=\"image/svg+xml\" href=\"/favicon.svg\"><style>\n\t\t\t:root { --bg-color: #050505; --accent-color: #ff0055; --text-color: #ffffff; --muted-color: #888888; --border-color: #ff0055; }\n\t\t\t* { box-sizing: border-box; margin: 0; padding: 0; }\n\t\t\tbody { background-color: var(--bg-color); color: var(--text-color); font-family: 'Courier New', Courier, monospace; display: flex; flex-direction: column; align-items: center; justify-content: center; min-height: 100vh; padding: 20px; text-align: center; }\n\t\t\t.container { max-width: 650px; width: 100%; border: 2px solid var(--border-color); padding: 40px 30px; box-shadow: 0 0 20px rgba(255, 0, 85, 0.4); background: #0a0a0a; }\n\t\t\th1 { color: var(--accent-color); font-size: 5rem; margin-bottom: 10px; text-transform: uppercase; letter-spacing: 5px; text-shadow: 0 0 10px rgba(255,0,85,0.5); }\n\t\t\th2 { color: #fff; font-size: 1.5rem; margin-bottom: 20px; text-transform: uppercase; }\n\t\t\tp { color: var(--muted-color); margin-bottom: 30px; font-size: 1.1rem; line-height: 1.5; }\n\t\t\t.btn { background: transparent; color: var(--accent-color); border: 2px solid var(--accent-color); padding: 15px 30px; font-size: 1.1rem; font-weight: bold; font-family: inherit; cursor: pointer; text-transform: uppercase; text-decoration: none; display: inline-block; transition: all 0.2s ease; }\n\t\t\t.btn:hover { background: var(--accent-color); color: #000; box-shadow: 0 0 15px var(--accent-color); }\n\t\t\t.glitch-block { background: #111; border: 1px dashed var(--muted-color); padding: 15px; font-size: 0.9rem; color: #ff9900; margin-bottom: 30px; text-align: left; overflow-x: auto; }\n\t\t</style></head><body><div class=\"container\"><h1>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", statusCode))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/error.templ`, Line: 28, Col: 38}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</h1><h2>SYSTEM ERROR</h2><div class=\"glitch-block\">&gt; EXCEPTION CAUGHT IN MAIN LOOP<br>&gt; DETAILS: ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(errorMessage)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/error.templ`, Line: 32, Col: 32}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<br>&gt; ALERT LEVEL: ELEVATED<br></div><p>Something went wrong on the grid. Verify your credentials or the terminal link.</p><a href=\"/\" class=\"btn\">⬅️ JACK OUT TO MAIN MENU</a></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
